[package]
name = "gap_effect_timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
crossterm = "0.26.1"
rand = "0.8.5"
rodio = "0.17.1"

[profile.release]
lto = true
opt-level = "s"
debug = false
strip = true
debug-assertions = false
incremental = true
codegen-units = 256
